repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: no-commit-to-branch
  - id: check-merge-conflict
  - id: check-yaml
    args: [ '--unsafe' ]
  - id: check-toml
  - id: end-of-file-fixer
  - id: trailing-whitespace

- repo: https://github.com/codespell-project/codespell
  rev: v2.4.1
  hooks:
  - id: codespell
    additional_dependencies:
    - tomli
    exclude: '^uv\.lock$'

- repo: https://github.com/astral-sh/uv-pre-commit
  rev: 0.6.6
  hooks:
  - id: uv-lock
  - id: uv-export
    args: [ "--output-file=requirements.txt" ]

- repo: https://github.com/commitizen-tools/commitizen
  rev: v4.4.1
  hooks:
  - id: commitizen
  - id: commitizen-branch
    stages:
    - post-commit

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.9.10
  hooks:
  - id: ruff
    args: [ --fix ]
  - id: ruff-format
