name: cd-build
description: Publish project wheels and sdist.

on:
  workflow_call:

jobs:
  buid-sdist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pdm-project/setup-pdm@v4.2
        with:
          python-version: '3.11'
      - name: build wheels
        run: pdm build --no-wheel
      - name: Upload built wheels and src code as artifacts
        uses: actions/upload-artifact@v4.6
        with:
          name: sdist
          path: dist/*

  build-wheels:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-13, macos-latest, windows-latest]
        python-version: ['3.11', '3.12']
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - uses: pypa/cibuildwheel@v2.22.0

      - name: Upload built wheels and src code as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ matrix.python-version }}
          path: ./wheelhouse/*.whl
