name: docs
description: Builds project documentation with mkdocs.

on:
  workflow_call:
    inputs:
      version:
        description: 'docs version'
        type: string
        required: false
      dry-run:
        type: boolean
        required: false
        default: false

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - uses: astral-sh/setup-uv@v5
      with:
        python-version: '3.11'

    - run: uv sync --group docs
    - run: uv run mkdocs build
    - name: publish website
      if: inputs.dry-run == false
      run: |
        echo "${{ inputs.version }}"
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"
        uv run mike deploy ${{ inputs.version }} latest --update-aliases --push
        uv run mike set-default latest
