name: release
description: Create a new semantic release.

on:
  workflow_call:
    outputs:
      version:
        value: ${{ jobs.release.outputs.version }}
      released:
        value: ${{ jobs.release.outputs.released }}
      sha:
        description: "The latest commit SHA after release"
        value: ${{ jobs.release.outputs.sha }}

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      sha: ${{ steps.get-sha.outputs.sha }}
      version: ${{ steps.release.outputs.version }}
      released: ${{ steps.release.outputs.released }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: "${{ secrets.GITHUB_TOKEN }}"
      - id: release
        name: Create bump and changelog (or dry-run)
        uses: python-semantic-release/python-semantic-release@v9.18.1
        with:
          root_options: "-vv"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          git_committer_name: "github-actions"
          git_committer_email: "actions@users.noreply.github.com"
      - id: get-sha
        run: echo "sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
